import { forwardRef } from "react";

// Drop-in replacement for a raw <img> that serves the AVIF/WebP siblings
// generated by `npm run images` (scripts/generate-image-formats.mjs) and
// falls back to the original file wherever those don't exist.
//
// Callers pass exactly what they pass an <img> today — the original
// `/images/foo.jpg` string path. The derivative paths are derived here by
// extension swap, so section data objects and the /figma-pull convention of
// emitting `/images/*.jpg` string paths stay unchanged.

// Whether this build's derivatives exist at all. The pipeline is
// production-only (scripts/image-formats.mjs), and vite.config.js bakes the
// same predicate in here as a literal, so on dev and staging every image
// takes the pass-through path below. Skipping that would be worse than
// wasteful: a <source> whose file 404s is not retried against the <img>, so
// advertising .avif we never encoded means no image renders at all.
const DERIVATIVES_ENABLED = import.meta.env.VITE_IMAGE_DERIVATIVES === true;

// Widths of the downscaled copies the generator writes beside each
// derivative (RESPONSIVE_WIDTHS in scripts/image-formats.mjs, baked in by
// vite.config.js). Every width exists for every image, so the srcset below
// never names a file that 404s.
const WIDTHS = import.meta.env.VITE_IMAGE_WIDTHS ?? [];

// Only the extensions the generator actually emits siblings for. Anything
// else (.svg, .gif, an already-optimised .webp) takes the pass-through path
// below rather than pointing a <source> at a file that would 404.
const CONVERTED_EXTENSIONS = /\.(?:jpe?g|png)$/i;

// Matches a scheme (`http:`, `https:`, `data:`, `blob:`) or a
// protocol-relative `//host/…`. A repo-local `/images/foo.jpg` has a single
// leading slash and no scheme, so it does not match.
const EXTERNAL_SRC = /^(?:[a-z][a-z0-9+.-]*:|\/\/)/i;

// Splits `/images/foo.jpg?v=2#frag` into the path and everything after it, so
// the extension swap only ever touches the path segment.
const PATH_AND_SUFFIX = /^([^?#]*)([\s\S]*)$/;

// Frozen and hoisted: one shared object rather than a fresh literal per
// <source> per render. See the long note at the return statement for why the
// <source> elements have to be taken out of flow at all.
const HIDDEN_SOURCE = Object.freeze({ display: "none" });

/**
 * Swaps the extension on the path portion of `src`, preserving any query
 * string or fragment.
 */
function withExtension(src, extension) {
  const [, path, suffix] = PATH_AND_SUFFIX.exec(src);

  return `${path.replace(CONVERTED_EXTENSIONS, "")}${extension}${suffix}`;
}

/** `foo-640.avif 640w, foo-960.avif 960w, …` for one format. */
function widthSrcSet(src, extension) {
  return WIDTHS.map(
    (width) => `${withExtension(src, `-${width}${extension}`)} ${width}w`
  ).join(", ");
}

function hasDerivatives(src) {
  if (!DERIVATIVES_ENABLED) return false;
  if (typeof src !== "string" || src === "") return false;
  if (EXTERNAL_SRC.test(src)) return false;

  const [, path] = PATH_AND_SUFFIX.exec(src);

  return CONVERTED_EXTENSIONS.test(path);
}

// Lazy by default: every current caller is below the fold (the masthead
// images go through MastheadImage's own <img>). Eager loads here were ~900 KB
// of AVIF downloading ahead of the masthead copy, all of which PageSpeed's
// simulated throttling billed to LCP. Pass loading="eager" for anything that
// can be the first thing on screen.
const Picture = forwardRef(function Picture(
  // sizes: the image's rendered width, for picking a srcset candidate.
  // Defaults to 100vw — right for the full-bleed mobile layouts PageSpeed
  // measures; pass something tighter where a desktop layout is narrower.
  { src, alt, loading = "lazy", decoding = "async", sizes = "100vw", ...rest },
  ref
) {
  const img = (
    <img
      ref={ref}
      src={src}
      alt={alt}
      loading={loading}
      decoding={decoding}
      {...rest}
    />
  );

  // Pass-through: no generated siblings exist for this source, so wrapping it
  // in a <picture> would only add a box to the layout for no benefit. This is
  // the path the 20 client-logo SVGs and chart.svg take.
  if (!hasDerivatives(src)) return img;

  // `contents` keeps <picture> out of layout entirely, so the <img> stays the
  // parent's direct grid/flex child and the classes on it keep resolving
  // against the box they did before this wrapper existed.
  //
  // HIDDEN_SOURCE is the other half of that, and is not optional. <source> is
  // NOT display:none in the UA stylesheet — it computes to display:block.
  // Normally that's invisible, because <picture> is the element in flow and
  // its <source> children generate no box. But `display: contents` above
  // hoists them into the parent flex/grid container as real, zero-sized
  // items, and the container's `gap` between them is very much not invisible:
  // every image was adding two extra gaps to its parent (+112px per card in
  // FromInsideOut's gap-700 grid, +64px in Proof/NewsAwards' gap-400, plus a
  // spurious implicit row in MediaObject). Taking the two <source> elements
  // out of flow restores the pre-<picture> box model exactly.
  //
  // Safe: the source-selection algorithm reads the DOM, not rendered boxes,
  // so a display:none <source> is still selected from — verified in-browser
  // (photos resolve to .avif with this rule applied). Inline style rather
  // than a class so the rule travels with the component instead of living in
  // src/index.css, where nothing connects it back to `contents` here.
  return (
    <picture className="contents">
      <source
        srcSet={widthSrcSet(src, ".avif")}
        sizes={sizes}
        type="image/avif"
        style={HIDDEN_SOURCE}
      />
      <source
        srcSet={widthSrcSet(src, ".webp")}
        sizes={sizes}
        type="image/webp"
        style={HIDDEN_SOURCE}
      />
      {img}
    </picture>
  );
});

export default Picture;
