import { forwardRef } from "react";

// Drop-in replacement for a raw <img> that serves the AVIF/WebP siblings
// generated by `npm run images` (scripts/generate-image-formats.mjs) and
// falls back to the original file wherever those don't exist.
//
// Callers pass exactly what they pass an <img> today — the original
// `/images/foo.jpg` string path. The derivative paths are derived here by
// extension swap, so section data objects and the /figma-pull convention of
// emitting `/images/*.jpg` string paths stay unchanged.

// Only the extensions the generator actually emits siblings for. Anything
// else (.svg, .gif, an already-optimised .webp) takes the pass-through path
// below rather than pointing a <source> at a file that would 404.
const CONVERTED_EXTENSIONS = /\.(?:jpe?g|png)$/i;

// Matches a scheme (`http:`, `https:`, `data:`, `blob:`) or a
// protocol-relative `//host/…`. A repo-local `/images/foo.jpg` has a single
// leading slash and no scheme, so it does not match.
const EXTERNAL_SRC = /^(?:[a-z][a-z0-9+.-]*:|\/\/)/i;

// Splits `/images/foo.jpg?v=2#frag` into the path and everything after it, so
// the extension swap only ever touches the path segment.
const PATH_AND_SUFFIX = /^([^?#]*)([\s\S]*)$/;

// Frozen and hoisted: one shared object rather than a fresh literal per
// <source> per render. See the long note at the return statement for why the
// <source> elements have to be taken out of flow at all.
const HIDDEN_SOURCE = Object.freeze({ display: "none" });

/**
 * Swaps the extension on the path portion of `src`, preserving any query
 * string or fragment.
 */
function withExtension(src, extension) {
  const [, path, suffix] = PATH_AND_SUFFIX.exec(src);

  return `${path.replace(CONVERTED_EXTENSIONS, "")}${extension}${suffix}`;
}

function hasDerivatives(src) {
  if (typeof src !== "string" || src === "") return false;
  if (EXTERNAL_SRC.test(src)) return false;

  const [, path] = PATH_AND_SUFFIX.exec(src);

  return CONVERTED_EXTENSIONS.test(path);
}

const Picture = forwardRef(function Picture({ src, alt, ...rest }, ref) {
  const img = <img ref={ref} src={src} alt={alt} {...rest} />;

  // Pass-through: no generated siblings exist for this source, so wrapping it
  // in a <picture> would only add a box to the layout for no benefit. This is
  // the path the 20 client-logo SVGs and chart.svg take.
  if (!hasDerivatives(src)) return img;

  // `contents` keeps <picture> out of layout entirely, so the <img> stays the
  // parent's direct grid/flex child and the classes on it keep resolving
  // against the box they did before this wrapper existed.
  //
  // HIDDEN_SOURCE is the other half of that, and is not optional. <source> is
  // NOT display:none in the UA stylesheet — it computes to display:block.
  // Normally that's invisible, because <picture> is the element in flow and
  // its <source> children generate no box. But `display: contents` above
  // hoists them into the parent flex/grid container as real, zero-sized
  // items, and the container's `gap` between them is very much not invisible:
  // every image was adding two extra gaps to its parent (+112px per card in
  // FromInsideOut's gap-700 grid, +64px in Proof/NewsAwards' gap-400, plus a
  // spurious implicit row in MediaObject). Taking the two <source> elements
  // out of flow restores the pre-<picture> box model exactly.
  //
  // Safe: the source-selection algorithm reads the DOM, not rendered boxes,
  // so a display:none <source> is still selected from — verified in-browser
  // (photos resolve to .avif with this rule applied). Inline style rather
  // than a class so the rule travels with the component instead of living in
  // src/index.css, where nothing connects it back to `contents` here.
  return (
    <picture className="contents">
      <source
        srcSet={withExtension(src, ".avif")}
        type="image/avif"
        style={HIDDEN_SOURCE}
      />
      <source
        srcSet={withExtension(src, ".webp")}
        type="image/webp"
        style={HIDDEN_SOURCE}
      />
      {img}
    </picture>
  );
});

export default Picture;
